# Default values for gitops setup

global:
  render: true
  argocd:
    enabled: true
    controller: openshift-operators
  operators: 
    enabled: true
  rbac: 
    enabled: true 
  namespace: openshift-operators
  domain: sandbox2646
  sno:
    1: 
      token: sha256~zzRcO2qehp2ixuVqbUmCQzkrR0laoSZTWUmt-o1ZHhM    
    2: 
      token: sha256~MYErqDS4Zbbndouvg_Zrn304-Csf0nV92SanK2S2C3I
    3: 
      token: sha256~8xe3G7BKpB_zFx7kbpLQsy6oR1lToaO7ig_xgR4tQ9s
