---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: day2-as-sno-4
  namespace: openshift-operators
spec:
  generators:
  - git:
      repoURL: https://github.com/romerobu/workshop-gitops-content-deploy.git
      revision: sno-4-setup
      files:
      - path: "../config-definition/**/config.json"
  template:
    metadata:
      name: 'day2-{{configuration}}-a'
    spec:
      project: default
      source:
        repoURL: https://github.com/romerobu/workshop-gitops-content-deploy.git
        targetRevision: sno-4
        path: .
        helm:
          valueFiles:
            - '{{valuesFile}}'        
      destination:
        server: 'https://kubernetes.default.svc'
        namespace: ''
      syncPolicy:
        automated:
          prune: true
          selfHeal: true 